version: "3.8"

services:
  mysql:
    build: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: itnpru6438@
      MYSQL_DATABASE: activitydb
      MYSQL_USER: itnpru6438
      MYSQL_PASSWORD: itnpru6438@
