version: "3.8"

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile  # Build using the custom Dockerfile
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: itnpru6438@
      MYSQL_DATABASE: activitydb
      MYSQL_USER: itnpru6438
      MYSQL_PASSWORD: itnpru6438@
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: itnpru6438@

volumes:
  mysql_data:
    driver: local
