# Use the MySQL base image
FROM mysql:5.7

# Set environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=itnpru6438@
ENV MYSQL_DATABASE=activitydb
ENV MYSQL_USER=itnpru6438
ENV MYSQL_PASSWORD=itnpru6438@

# Expose the MySQL port
EXPOSE 3306