# ใช้ภาพพื้นฐาน MySQL
FROM mysql:5.7

# ตั้งค่าตัวแปรสภาพแวดล้อม
ENV MYSQL_ROOT_PASSWORD=itnpru6438@
ENV MYSQL_DATABASE=activitydb
ENV MYSQL_USER=itnpru6438
ENV MYSQL_PASSWORD=itnpru6438@

# กำหนดพอร์ตที่ MySQL จะทำงาน
EXPOSE 3333
